### ISSUE TITLE
composer installation won't work

### ISSUE THREAD

**Issue by anthonykozak** [crscheid/php-article-extractor#19]
composer require crscheid/php-article-extractor
Using version ^0.6.0 for crscheid/php-article-extractor
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for crscheid/php-article-extractor ^0.6.0 -> satisfiable by crscheid/php-article-extractor[0.6].
    - crscheid/php-article-extractor 0.6 requires scotteh/php-goose dev-master -> satisfiable by scotteh/php-goose[dev-master] but these conflict with your requirements or minimum-stability.

Installation failed, deleting ./composer.json.

**Comment by crscheid** [comment]
Can you post the composer.json file that you are using to include this package. The package standalone installs fine.

**Comment by crscheid** [comment]
Closing issue.
