### ISSUE TITLE
301 redirects to incomplete URL 

### ISSUE THREAD

**Issue by bogdangrab** [crscheid/php-article-extractor#23]
Hey,

Found an issue where when checking for redirects and one is detected, the new_url will end up from something like this https://www.bbc.co.uk/news/uk-politics-47379565 to something like /news/some-other-path/uk-politics-47379565 (this occurs when the target URL is passed without the domain and scheme).

**Comment by crscheid** [comment]
Got it. Thanks for submitting and will add this to the to-do list for fixes.

**Comment by crscheid** [comment]
@bogdangrab Apologize for the long delay. I forgot this issue was present until I ran into it again.
